# Assignment 04
**Author**: Crista Barnes

**Date**: 2/26/2021

Open census_cost.txt into line_list and print one line at a time using a loop

In [1]:
with open("census_cost.txt", "rt") as f:
    line_list = f.readlines()
for row in line_list:
    print(row)

Source: https://www.genealogybranches.com/censuscosts.html

Census Year	Total Population	Census Cost	Average Cost Per Person

1790	3,929,214	$44,377	1.13 cents

1800	5,308,483	$66,109	1.24 cents

1810	7,239,881	$178,445	2.46 cents

1820	9,633,822	$208,526	2.16 cents

1830	12,866,020	$378,545	2.94 cents

1840	17,069,458	$833,371	4.88 cents

1850	23,191,876	$1,423,351	6.14 cents

1860	31,443,321	$1,969,377	6.26 cents

1870	38,558,371	$3,421,198	8.87 cents

1880	50,155,783	$5,790,678	11.54 cents

1890	62,979,766	$11,547,127	18.33 cents

1900	76,303,387	$11,854,000	15.54 cents

1910	91,972,266	$15,968,000	17.07 cents

1920	105,710,620	$25,117,000	23.76 cents

1930	122,775,046	$40,156,000	32.71 cents

1940	131,669,275	$67,527,000	51.29 cents

1950	151,325,798	$91,462,000	60.44 cents

1960	179,323,175	$127,934,000	71.34 cents

1970	203,302,031	$247,653,000	$1.22

1980	226,542,199	$1,078,488,000	$4.76

1990	248,718,301	$2,492,830,000	$10.02

2000	281,421,906	$4.5 Billion	$15.99

2010*	308,745,538	$13 Billion	$42.11

Extract the first two lines of line_list and print them

In [2]:
top2_list=line_list[:2]
for row in top2_list:
    print(row)

Source: https://www.genealogybranches.com/censuscosts.html

Census Year	Total Population	Census Cost	Average Cost Per Person

Extract the data from line_list and print

In [3]:
data_list=line_list[2:]
for row in data_list:
    print(row)

1790	3,929,214	$44,377	1.13 cents

1800	5,308,483	$66,109	1.24 cents

1810	7,239,881	$178,445	2.46 cents

1820	9,633,822	$208,526	2.16 cents

1830	12,866,020	$378,545	2.94 cents

1840	17,069,458	$833,371	4.88 cents

1850	23,191,876	$1,423,351	6.14 cents

1860	31,443,321	$1,969,377	6.26 cents

1870	38,558,371	$3,421,198	8.87 cents

1880	50,155,783	$5,790,678	11.54 cents

1890	62,979,766	$11,547,127	18.33 cents

1900	76,303,387	$11,854,000	15.54 cents

1910	91,972,266	$15,968,000	17.07 cents

1920	105,710,620	$25,117,000	23.76 cents

1930	122,775,046	$40,156,000	32.71 cents

1940	131,669,275	$67,527,000	51.29 cents

1950	151,325,798	$91,462,000	60.44 cents

1960	179,323,175	$127,934,000	71.34 cents

1970	203,302,031	$247,653,000	$1.22

1980	226,542,199	$1,078,488,000	$4.76

1990	248,718,301	$2,492,830,000	$10.02

2000	281,421,906	$4.5 Billion	$15.99

2010*	308,745,538	$13 Billion	$42.11

In [4]:
#Split each row in data_list with '\t' 
#This will result in four sublists of data_list, one for each column
for i in range(0, len(data_list)):
    data_list[i]=data_list[i].split('\t')

In [5]:
#Test to ensure the first element of the first row is what is expected
data_list[0][0]

'1790'

Extract the column Census Year, clean, and display

In [6]:
#Create an empty list for the first column
year_list=[]
for i in range(0, len(data_list)):
    #Append each year to year_list
    year_list.append(data_list[i][0])
    #If there is an extra character (*) in the year, delete it
    if len(year_list[i])>4:
        year_list[i]=year_list[i].replace('*','')
for row in year_list:
    print(row)

1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010

Extract the column Total Population, clean, and display

In [7]:
#Create an empty list for the second column
pop_list=[]
for i in range(0, len(data_list)):
    #Append each population count to pop_list
    pop_list.append(data_list[i][1])
    #Remove the ',' in each number
    pop_list[i]=pop_list[i].replace(',','')
for row in pop_list:
    print(row)

3929214
5308483
7239881
9633822
12866020
17069458
23191876
31443321
38558371
50155783
62979766
76303387
91972266
105710620
122775046
131669275
151325798
179323175
203302031
226542199
248718301
281421906
308745538

Extract the column Census Cost, clean, and display

In [8]:
#Create an empty list for the third column
cost_list=[]
for i in range(0, len(data_list)):
    #Append each Census Cost to cost_list
    cost_list.append(data_list[i][2])
    #Remove the ',' and '$' from each number
    cost_list[i]=cost_list[i].replace(',','')
    cost_list[i]=cost_list[i].replace('$','')
    if 'Billion' in cost_list[i]:
        cost_list[i]=cost_list[i].replace('Billion','')
        cost_list[i]=str(int(float(cost_list[i])*1000000000))
        
#Remove 'Billion' and add '0's to those values 
#cost_list[21]='4500000000'
#cost_list[22]='13000000000'
for row in cost_list: 
    print(row)

44377
66109
178445
208526
378545
833371
1423351
1969377
3421198
5790678
11547127
11854000
15968000
25117000
40156000
67527000
91462000
127934000
247653000
1078488000
2492830000
4500000000
13000000000

Extract the column Average Cost Per Person, clean, and display

In [9]:
#Create an empty list for the forth column
avg_list=[]
for i in range(0, len(data_list)):
    #Append the Avg Cost data to avg_list
    avg_list.append(data_list[i][3])
    #If the value is in cents, remove 'cents', and divide number by 100 to display value in dollars 
    if 'cents' in avg_list[i]:
        avg_list[i]=avg_list[i].replace(' cents','')
        avg_list[i]=str(round(float(avg_list[i])/100,2))
    #If the value is in dollars, remove the '$'
    if '$' in avg_list[i]:
        avg_list[i]=avg_list[i].replace('$','')
    #Remove the '\n' from each item in list
    avg_list[i]=avg_list[i].replace('\n','')
for row in avg_list:
    print(row)

0.01
0.01
0.02
0.02
0.03
0.05
0.06
0.06
0.09
0.12
0.18
0.16
0.17
0.24
0.33
0.51
0.6
0.71
1.22
4.76
10.02
15.99
42.11

Consolidate the new data to a csv file

In [10]:
#Open a new csv file to put cleansed data
with open("census_cost.csv", "wt") as f:
    #While writing data to the new file, replace '\t' with ',' in the top two lines
    for line in top2_list[0:]:
        f.write(line.replace("\t", ","))
    #While writing data to the new file, add a comma after each column item, and a new line after the last column 
    for line in range(0, len(year_list)):
        f.write(year_list[line]+',')
        f.write(pop_list[line]+',')
        f.write(cost_list[line]+',')
        f.write(avg_list[line]+'\n')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=eb0a1b1e-7717-4570-b08b-c403cebb0472' target="_blank">
<img style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>